-- תיקון טיפוסי נתונים בטבלאות
ALTER TABLE part ALTER COLUMN name TYPE VARCHAR(100);
ALTER TABLE part ALTER COLUMN last_update TYPE DATE;

ALTER TABLE employees ALTER COLUMN name TYPE VARCHAR(100);
ALTER TABLE employees ALTER COLUMN role TYPE VARCHAR(50);
ALTER TABLE employees ALTER COLUMN start_date TYPE DATE;
ALTER TABLE employees ALTER COLUMN last_training TYPE DATE;

ALTER TABLE warehouses ALTER COLUMN location TYPE VARCHAR(100);
ALTER TABLE warehouses ALTER COLUMN open_date TYPE DATE;

ALTER TABLE suppliers ALTER COLUMN name TYPE VARCHAR(100);
ALTER TABLE suppliers ALTER COLUMN phone TYPE VARCHAR(20);

ALTER TABLE costumers ALTER COLUMN phone TYPE VARCHAR(20);
ALTER TABLE costumers ALTER COLUMN email TYPE VARCHAR(100);
ALTER TABLE costumers ALTER COLUMN registration_date TYPE DATE;

ALTER TABLE warehouseparts ALTER COLUMN last_updated TYPE DATE;

ALTER TABLE SupplierParts ALTER COLUMN price TYPE DECIMAL(10,2);

ALTER TABLE myorder ALTER COLUMN order_date TYPE DATE;
ALTER TABLE myorder ALTER COLUMN arrival_date TYPE DATE;

ALTER TABLE costumer_warehous_storage ALTER COLUMN start_date TYPE DATE;
ALTER TABLE costumer_warehous_storage ALTER COLUMN end_date TYPE DATE;

ALTER TABLE trains ALTER COLUMN model TYPE VARCHAR(50);
ALTER TABLE trains ALTER COLUMN last_check TYPE DATE;
ALTER TABLE trains ALTER COLUMN next_check TYPE DATE;

ALTER TABLE Hub ALTER COLUMN Name TYPE VARCHAR(100);
ALTER TABLE Hub ALTER COLUMN Location TYPE VARCHAR(100);
ALTER TABLE Hub ALTER COLUMN IATA_code TYPE VARCHAR(3);

ALTER TABLE Hangar ALTER COLUMN Name TYPE VARCHAR(100);
ALTER TABLE Hangar ALTER COLUMN Location TYPE VARCHAR(100);

ALTER TABLE Producer ALTER COLUMN Pname TYPE VARCHAR(100);
ALTER TABLE Producer ALTER COLUMN Owner TYPE VARCHAR(100);
ALTER TABLE Producer ALTER COLUMN EstDate TYPE DATE;

ALTER TABLE Plane ALTER COLUMN Status TYPE VARCHAR(20);
ALTER TABLE Plane ALTER COLUMN ProductionDate TYPE DATE;
ALTER TABLE Plane ALTER COLUMN Model TYPE VARCHAR(50);

ALTER TABLE Operator ALTER COLUMN Type TYPE VARCHAR(50);
ALTER TABLE Operator ALTER COLUMN Name TYPE VARCHAR(100);

ALTER TABLE Pilot ALTER COLUMN Rank TYPE VARCHAR(50);
ALTER TABLE Pilot ALTER COLUMN License_num TYPE VARCHAR(20);
ALTER TABLE Pilot ALTER COLUMN Name TYPE VARCHAR(100);

ALTER TABLE Pilot_Plane ALTER COLUMN Assignment_date TYPE DATE;

-- הוספת שדות נוספים לשיפור הפונקציונליות
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS manager_id INT REFERENCES employees(employee_id);
ALTER TABLE Plane ADD COLUMN IF NOT EXISTS last_maintenance DATE;
ALTER TABLE Plane ADD COLUMN IF NOT EXISTS flight_hours INT DEFAULT 0;